apiVersion: v1
kind: Service
metadata:
  name: app-d-service
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: app-d
  sessionAffinity: None
  type: ClusterIP