apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-desafio
  region: us-east-1

vpc:
  id: "vpc-09e43f38fec4055a0"
  securityGroup: "sg-0de1983f7e33104ee"
  sharedNodeSecurityGroup: "sg-0f36eb5ee88ff2f41"
  manageSharedNodeSecurityGroupRules: true 
  subnets:
    private:
      us-east-1a:
        id: "subnet-05bba73baa7c2b945"
      us-east-1b:
        id: "subnet-0e356025278f013a2"

managedNodeGroups:
  - name: desafio-ng
    instanceType: t2.micro
    amiFamily: AmazonLinux2
    privateNetworking: true
    volumeSize: 20 
    desiredCapacity: 3
    minSize: 2
    maxSize: 6
    iam:
      withAddonPolicies:
        autoscaler: true
        externalDNS: true
        certManager: true
        cloudWatch: true

    